Repository ministryofjustice/laa-access-civil-legal-aid, pull requests merged in 2025-06, with the labels that each got.

#277 LGA-3717 GovUK Rebrand
  app/config/__init__.py
  app/templates/base.html
  package-lock.json
  package.json
  requirements/generated/requirements-development.txt
  requirements/generated/requirements-production.txt
Labels: Approval 1, Approval 2

#275 LGA-3698 improve documentation
  .github/workflows/build-docs.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main-branch.yml
  .trufflehog3.yml
  README.md
  app/find_a_legal_adviser/README.md
  docs/README.md
  docs/config/tech-docs.yml
  docs/makefile
  docs/source/documentation/callbacks.html.md.erb
  docs/source/documentation/case-booking.html.md.erb
  docs/source/documentation/categories.html.md.erb
  docs/source/documentation/contact-us.html.md.erb
  docs/source/documentation/fala.html.md.erb
  docs/source/documentation/fast-track.html.md.erb
  docs/source/documentation/index.html.md.erb
  docs/source/documentation/means-test.html.md.erb
  docs/source/documentation/notify.html.md.erb
  docs/source/documentation/session.html.md.erb
  docs/source/images/civil_case_data_erd.png
  docs/source/index.html.md.erb
  docs/source/javascripts/application.js
  docs/source/stylesheets/screen.css.scss
Labels: Approval 1

#281 Fix published documentation
  .github/workflows/build-docs.yml
  .github/workflows/feature-branch.yml
  docs/config/tech-docs.yml
  docs/makefile
  docs/source/documentation/callbacks.html.md.erb
  docs/source/documentation/fast-track.html.md.erb
  docs/source/documentation/index.html.md.erb
  docs/source/documentation/notify.html.md.erb
Labels: Approval 1, Approval 2

#284 LGA-3759: Fix rebrand not applying automatically
  app/config/__init__.py
  app/main/__init__.py
  app/templates/base.html
Labels: Approved
